language: en

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
    model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 10
