language: en
pipeline:
- name: HFTransformersNLP
  model_weights: "bert-base-uncased"
  model_name: "bert"
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 2
- name: DIETClassifier
  epochs: 43
  hidden_layers_sizes:
    text: [256]
  number_of_transformer_layers: 4
  embedding_dimension: 20
  transformer_size: 512

